### model
model_name_or_path: /root/code-assistant/models/Qwen2.5-Coder-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 128
lora_dropout: 0.05

### dataset
dataset: sft_pyfunc
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /root/code-assistant/training/sft_ckpt_full_0319
logging_steps: 50
save_steps: 2000
plot_loss: false
overwrite_output_dir: false
report_to: none

### train
per_device_train_batch_size: 6
gradient_accumulation_steps: 3
learning_rate: 2.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
gradient_checkpointing: true
packing: true
flash_attn: fa2
